import ProjectDescription

let workspace = Workspace(
    name: "PolymorphWorkSpace",
    projects: [
        "App/**",
        "Domain/**",
        "Core/**",
        "Shared/**",
        "Feature/**",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
